CC = cc
CFLAGS = -std=c99 -pedantic -Wall

all: intrep

messages.o : messages.c messages.h
	$(CC) -c messages.c

read_integers.o: read_integers.c read_integers.h
	$(CC) -c read_integers.c
	
intrep: main.c messages.o read_integers.o
	$(CC) main.c messages.o read_integers.o  -o intrep

clean:
	rm -rf intrep *.o *~
